### ISSUE TITLE
Any way to use as express middleware?

### ISSUE THREAD

**Issue by blackwood** [JackuB/apish#124]
Can the Promise returned by `apish()` be utilized as Express middleware? It would be useful to see more specific documentation on what can be done with that returned promise.

**Comment by JackuB** [comment]
Yea, I was thinking about having a way to filter which resources will get mocked and which won't. That would allow you to create scenarios, by selecting a response pair from a resource. But I'm not sure about what would be the best way to describe the filter. [Dredd transactions](https://github.com/apiaryio/dredd-transactions) are closest thing I can imagine, but they aren't exactly friendly if you'd be writing them from scratch in your tests. And `name`, which was closest is already deprecated https://github.com/apiaryio/dredd-transactions#deprecated-properties

I think having a `filter()` function would be the most customisable.

```js
apish.filter((resource) => {
  if (resource.method === 'get' && resource.path === '/music') {
    return true
  }
  return false
})
```

Thoughts?

**Comment by JackuB** [comment]
I'm closing this one, feel free to reopen if there is any more input
