### ISSUE TITLE
Problem with parameters in URL and URITemplate

### ISSUE THREAD

**Issue by snakeye** [JackuB/apish#165]
Hello!

I'm trying to implement API tests with apish and looks like I've found a problem. 

Consider the following API endpoints:

```
http://www.example.com:80/users/{user}/
http://www.example.com:80/users/{user}/posts/
```

In file `create-mocks.js:28` the filtering path function will match API call `/users/example/posts/` to the first endpoint due to nature of the URI Template - they use regexp `/(.*)/$` to extract parameters.

**Comment by JackuB** [comment]
Nice catch, I'll take a look

**Comment by jesprider** [comment]
Hey @JackuB, what's the status of this one? Could you please take a look at the PR from @snakeye?
